### ISSUE TITLE
SQLiteDatabase: Error 

### ISSUE THREAD

**Issue by xybCoder** [CPPAlien/ChatKeyboard#13]
SQLiteDatabase: Error inserting row=4 item_padding=30 horizontal_spacing=0 is_show_del_btn=0 name=sme line=2 icon_uri=assets://emoticons/sme/wg_tab.png vertical_spacing=0 is_show_name=true
                                                                           android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: emoticonset.name (code 2067)
                                                                               at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
                                                                               at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:782)
                                                                               at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:788)
                                                                               at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:86)
                                                                               at android.database.sqlite.SQLiteDatabase.insertWithOnConflict(SQLiteDatabase.java:1471)
                                                                               at android.database.sqlite.SQLiteDatabase.insert(SQLiteDatabase.java:1341)
                                                                               at cn.hadcn.keyboard.emoticon.db.EmoticonDBHelper.insertEmoticonSet(EmoticonDBHelper.java:105)
                                                                               at cn.hadcn.keyboard.ChatKeyboardLayout$5.run(ChatKeyboardLayout.java:704)
                                                                               at java.lang.Thread.run(Thread.java:818)

**Comment by CPPAlien** [comment]
Do you use the ChatKeyboardLayout.isEmoticonInitSuccess(this) before use init emoticon. This version of the lib, you can only init emoticon content for once.
